
<div class="featuredItem_Oglas">
<h2 class="naslovPrikaz_Oglas"><?php echo $this->escape ( ucfirst($this->naslov) ); ?></h2>

<div class="cenaPrikazMali_Oglas" style="display:block; margin-right:20px;">
<?php
if ($this->cena == 0) {
	echo "Cena po dogovoru";
} else {
	echo number_format($this->escape ( $this->cena )) . " " . $this->escape ( $this->valuta );
}

?></div>
<br>
<div  style="display:block; float:left; width:440px; color:black; line-height:normal; margin:5px;padding:3px; font-size:14px; text-align:left;">
<?php 
$def_img = "/images/upload/slikeoglasa/NisOglasi.jpg";
if( $this->escape ( $this->glavna_slika ) != $def_img
   || $this->escape ( $this->slika_dva ) != $def_img
   || $this->escape ( $this->slika_tri ) != $def_img
   || $this->escape ( $this->slika_cetri ) != $def_img
)
{
?>
<div class="gallery" id="gallery_<?php echo $this->id_oglasa; ?>">
<label style="font-size:14px;">Slike:</label>
<ul>
<?php 
   if($this->glavna_slika != $def_img)
   {
      $thumb = $this->glavna_slika . ".thumb.jpg";
      
      if(is_file(APP_PUBLIC . $thumb))
         $slika = $thumb;
      else 
         $slika = $this->glavna_slika;
      
      ?>
        <li>
         <a href='<?php
         	echo $this->escape ( $this->baseUrl ( $this->glavna_slika ) );?>' title="Nis oglasi - <?php echo $this->escape ( $this->naslov )?>">
         <img title="Klikni za uvećanje"
         	alt="Nis oglasi - <?php
         	echo $this->escape ( $this->naslov )?>"
         	src="<?php
         	echo $this->escape ( $this->baseUrl ( $slika ) );
         	?>"></a>
         	</li>
   	<?php 
   }
    
   if($this->slika_dva != $def_img)
   {
      $thumb = $this->slika_dva . ".thumb.jpg";
      if(is_file(APP_PUBLIC . $thumb))
         $slika = $thumb;
      else 
         $slika = $this->slika_dva;
      ?>
       <li>
      <a href='<?php
      	echo $this->escape ( $this->baseUrl ( $this->slika_dva ) );?>' title="Nis oglasi - <?php echo $this->escape ( $this->naslov )?>">
      <img title="Klikni za uvećanje"
      	alt="Nis oglasi - <?php
      	echo $this->escape ( $this->naslov )?>"
      	src="<?php
      	echo $this->escape ( $this->baseUrl ( $slika ) );
      	?>"></a>
      	</li>
   	<?php 
   }

   if($this->slika_tri != $def_img)
   {
      $thumb = $this->slika_tri . ".thumb.jpg";
      if(is_file(APP_PUBLIC . $thumb))
         $slika = $thumb;
      else 
         $slika = $this->slika_tri;
      ?>
       <li>
      <a href='<?php
      	echo $this->escape ( $this->baseUrl ( $this->slika_tri ) );?>' title="Nis oglasi - <?php echo $this->escape ( $this->naslov )?>">
      <img title="Klikni za uvećanje"
      	alt="Nis oglasi - <?php
      	echo $this->escape ( $this->naslov )?>"
      	src="<?php
      	echo $this->escape ( $this->baseUrl ( $slika ) );
      	?>"></a>
      	</li>
   	<?php 
   }
   
   $style4 = "";
   if( ($this->glavna_slika != $def_img)
      && ($this->escape ( $this->slika_dva ) != $def_img)
      && ($this->escape ( $this->slika_tri ) != $def_img) )
   {
      $style4 = "style=''";
   }
   if($this->slika_cetri != $def_img)
   {
      $thumb = $this->slika_cetri . ".thumb.jpg";
      if(is_file(APP_PUBLIC . $thumb))
         $slika = $thumb;
      else 
         $slika = $this->slika_cetri;
      ?>
       <li>
      <a href='<?php
      	echo $this->escape ( $this->baseUrl ( $this->slika_cetri ) );?>' title="Nis oglasi - <?php echo $this->escape ( $this->naslov )?>">
      <img  <?php echo $style4;?> title="Klikni za uvećanje"
      	alt="Nis oglasi - <?php
      	echo $this->escape ( $this->naslov )?>"
      	src="<?php
      	echo $this->escape ( $this->baseUrl ( $slika ) );
      	?>"></a>
      	</li>
   	<?php 
   }
?>
</ul>
</div>
<label style="width:100%; display:block; font-size:12px;">(Klikni na sliku za uvećanje)</label>
<script type="text/javascript">
    $(function() {
        $('#gallery_<?php echo $this->id_oglasa; ?> a').lightBox();
    });
</script>
<?php 
}
?>
<div style="float:left; width:440px;">
<p style='font-size:14px; padding:3px; margin:5px;'>
<?php 
echo  htmlspecialchars(ucfirst ($this->detalji)) ."<br>";
?>
</p>
<br>
<div class="gradPrikazMali_Oglas">
<p style='font-size:12px; padding:3px; margin:5px; line-height:24px;'>
<?php 
if(strtotime($this->datum_kreiranja) > (time() - 3*24*60*60))
{
?>
<label style="margin:5px; padding:2px; border:1px solid white; background-color:#FF6666; font-size:10px; color:white;">
Novo!</label>
<br>
<br>
<?php 
}
?>

<?php echo $this->partialLoop()->view->kategorije[$this->id_kategorije]; ?>,
<?php echo $this->partialLoop()->view->podkategorije[$this->id_podkategorije]['label']; ?>
<br><br>
<?php
if($this->adresa || $this->telefoni || $this->email || $this->sajt)
   echo "Kontakt podaci:&nbsp;<br>";
   
if( $this->telefoni )
   echo "Telefon(i): " . htmlspecialchars(ucfirst ($this->telefoni)) . "<br>";

if( $this->email )
   echo "Email: <a href='mailto:". $this->escape ( $this->email ) ."'>". htmlspecialchars($this->email) . "</a><br>";

if( $this->sajt && !(strstr($this->sajt,"oglasinis.com")))
   echo "Web sajt: <a href='http://" . $this->escape ( $this->sajt ) . "'>" . htmlspecialchars($this->sajt) . "</a><br>";   
   
if($this->adresa)
    echo "Adresa: " . htmlspecialchars(ucfirst ($this->adresa)) . "<br>";
   
if($this->grad)
   echo "Grad: ". $this->escape ( $this->grad ) . "<br>";

if(strtotime($this->datum_kreiranja))
{
   $dat_kreiranja = strtotime($this->datum_kreiranja);
   echo "Oglas predat: " . date("d.m.Y H:i", $dat_kreiranja) ." h<br>";
   echo "Oglas ističe: " . date("d.m.Y", strtotime("+2 month", $dat_kreiranja)) . " 23:59 h<br>";
}
?>
</p>
</div>
</div>
</div>
</div>

<?php 

   if( ( ($this->partialLoop()->view->currentItemCount == $this->partialLoop()->view->itemCountPerPage) 
      && ($this->partialCounter == intval($this->partialLoop()->view->itemCountPerPage/2)) )
      || ( $this->partialLoop()->view->currentItemCount == $this->partialCounter )
       )
   {
?>
<div class="featuredItem_Oglas">
<h2 class="naslovPrikaz_Oglas">Google Oglasi</h2>
<br>
<div  style="display:block; float:left; width:440px; color:black; line-height:normal; margin:5px;padding:3px; font-size:14px; text-align:center;">
&nbsp;
<?php if( $this->partialLoop()->view->currentItemCount == $this->partialCounter ){?>
<script type="text/javascript"><!--
google_ad_client = "ca-pub-6886463345124445";
/* donji sredina */
google_ad_slot = "1031504405";
google_ad_width = 336;
google_ad_height = 280;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<?php }else{?>
<script type="text/javascript"><!--
google_ad_client = "ca-pub-6886463345124445";
/* srednji sredina */
google_ad_slot = "4124571602";
google_ad_width = 336;
google_ad_height = 280;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<?php }?>
</div>
</div>
<?php 
   }
?>
