<div class="paginationControl_Oglas">
Strana: <?php echo $this->current; ?> / <?php echo $this->pageCount; ?>
<br>
<?php

if($this->pageCount > 1)
{
?>
<!-- Numbered page links -->
<?php
	for ($page = 1; $page <= $this->pageCount; $page++)
	{
		if ($page != $this->current) 
		{
			?>
<a title="Strana <?php echo $page;?>"
	href="<?php
			echo $this->url ( array_merge ( $this->params, array ('page' => $page ) ) );?>"><?php echo $page; ?></a>
<?php 
		}
		else 
		{
			echo $page;
		}
		echo " ";
		if($page < $this->pageCount)
		   echo "| ";
		
	}
}
?>
</div>