<div class="paginationControl_Oglas">
Strana: <?php echo $this->current; ?> od <?php echo $this->pageCount; ?>
<br>

<?php
if($this->current > 1)
{
   if($this->pageCount > 3)
      echo "<a title='Prva strana' href=\"". 
         $this->url ( array_merge ( $this->params, array ('page' => 1 ) ) ) ."\">&laquo;&laquo; Prva</a>";
       
   
   echo "<a title='Prethodna strana' href=\"". 
    $this->url ( array_merge ( $this->params, array ('page' => ($this->current - 1) ) ) ) ."\">&laquo; Prethodna</a>";
}
else 
{
   if($this->pageCount > 3)
      echo "<a title='Prva strana' style='color:#524E47;'>&laquo;&laquo; Prva</a>";
   echo "<a title='Prethodna strana' style='color:#524E47;'>&laquo; Prethodna</a>";
}

if($this->current < $this->pageCount)
{
   echo "<a title='Sledeća strana' href=\"". 
      $this->url ( array_merge ( $this->params, array ('page' => ($this->current + 1) ) ) ) ."\">Sledeća &raquo;</a>";
       
   if($this->pageCount > 3)
      echo "<a title='Poslednja strana' href=\"". 
         $this->url ( array_merge ( $this->params, array ('page' => $this->pageCount ) ) ) ."\">Poslednja &raquo;&raquo;</a>";
}
else
{
   echo "<a title='Sledeća strana' style='color:#524E47;'>Sledeća &raquo;</a>";
   if($this->pageCount > 3)
      echo "<a title='Poslednja strana' style='color:#524E47;'>Poslednja &raquo;&raquo;</a>";
}


if($this->pageCount > 1)
{
?>
<br><br>
<!-- Numbered page links -->
<?php
	for ($page = 1; $page <= $this->pageCount; $page++)
	{
		if ($page != $this->current) 
		{
			?>
<a title="Strana <?php echo $page;?>"
	href="<?php
			echo $this->url ( array_merge ( $this->params, array ('page' => $page ) ) );?>"><?php echo $page; ?></a>
<?php 
		}
		else 
		{
			echo $page;
		}
		echo " ";
		if($page < $this->pageCount)
		   echo "| ";
	}
}
?>
</div>