<?php
if ($this->pageCount) {
	// you need to add each of the request parameters to url
	$params = Zend_Controller_Front::getInstance ()->getRequest ()->getParams ();
	// remove the system parameters
	unset ( $params ['module'] );
	unset ( $params ['controller'] );
	unset ( $params ['action'] );
	//unset ( $params ['sort'] );
	
	?>
<div class="paginationControl_Oglas"><!-- Previous page link -->
<?php
	if (isset ( $this->previous )) {
		?>
<a
	href="<?php
		echo $this->url ( array_merge ( $params, array ('page' => $this->previous ) ) );
		?>"> Prethodni </a> |
<?php
	} else {
		?>
<span class="disabled"> Prethodni</span> |
<?php
	}
	?>
<!-- Numbered page links -->
<?php
	foreach ( $this->pagesInRange as $page ) {
		?>
<?php

		if ($page != $this->current) {
			?>
<a
	href="<?php
			echo $this->url ( array_merge ( $params, array ('page' => $page ) ) );
			?>">
<?php
			echo $page;
			?>
</a> |
<?php
		} else {
			?>
<?php

			echo $page;
			?> |
<?php
		}
	}
	?>
<!-- Next page link -->
<?php
	if (isset ( $this->next )) {
		?>
<a
	href="<?php
		echo $this->url ( array_merge ( $params, array ('page' => $this->next ) ) );
		?>"> Sledeći </a>
<?php
	} else {
		?>
<span class="disabled">Sledeći</span>
<?php
	}
	?>
</div>
<?php
}
?>