<h1>Svi oglasi na jednom mestu</h1>

<?php

if ($this->paginator->count () > 0) {
	?>
<br>
<br>
<?php
	echo $this->paginationControl ( $this->paginator, 'Sliding', 'partials/_page-adminpaginationcontrol.phtml' );
	?>

<table class="userListaPrikaz_oglas"  cellpadding='0' cellspacing='0'>
	<tr>
		<th>Opcije</th>
		<th><a
			href='<?php
	echo $this->baseUrl ( '/oglas/admin/listaadmin/sort/naslov' );
	?>'>Naslov oglasa</a></th>
		<th><a
			href='<?php
	echo $this->baseUrl ( '/oglas/admin/listaadmin/sort/datum_kreiranja' );
	?>'>Datum unosa</a></th>
		<th><a
			href='<?php
	echo $this->baseUrl ( '/oglas/admin/listaadmin/sort/proveren' );
	?>'>Status provere</a></th>
	</tr>


<?php
	echo $this->partialLoop ( 'partials/_page-adminoglasiprikaz.phtml', $this->paginator );
	?>
</table><?php
	echo $this->paginationControl ( $this->paginator, 'Sliding', 'partials/_page-adminpaginationcontrol.phtml' );

} else {
	?><br>
<h2>Nema unetih oglasa</h2>
<?php
}
?>














