<h2>Lista svih oglasa</h2>
<?php
if ($this->oglasi != null) {
	
	?>
<table class='spreadsheet' cellpadding='0' cellspacing='0'>
	<tr>
		<th><a
			href="<?php
	echo $this->baseUrl ( '/oglas/admin/listauser/sort/name' )?>">Naziv
		oglasa</a></th>
		<th><a
			href="<?php
	echo $this->baseUrl ( '/oglas/admin/listauser/sort/date_created' )?>">Datum
		unosa</a></th>

	</tr>
<?php
	echo $this->partialLoop ( 'admin/_page-userrow.phtml', $this->oglasi );
	?>
</table>
<?php
} else {
	?>
<p>Nemate unetih oglasa</p>
<a class="unosOglasaRight_Oglas"
	href='<?php
	echo $this->baseUrl ( 'oglas/unosoglasa/ ' );
	?>'> DODAJ OGLAS </a>
<?php

}
?>