<p>Ukupno dodato <?php
echo $this->ukupnododato;
?> novih email adresa.</p>
<p>Ukupno email adresa u bazi: <?php
echo $this->ukupno;
?>.</p>
<p>Ukupno email adresa za sva obavestenja: <?php
echo $this->svimasesalje;
?>.</p>
<p>Ukupno email adresa kojima se nista ne salje: <?php
echo $this->nista;
?>.</p>
<p>Ukupno email adresa kojima se salje samo po odredjenim kategorijama: <?php
echo $this->custom;
?>.</p>

