<style>
<!--
table{
	margin:10px;
	
}
table th{
	border:1px solid black;
}
table td{
	border:1px solid black;
}
-->
</style>
<h2>Korisnici</h2>

<?php 
if($this->users != null)
{
	?>
	<table class='spreadsheet' cellpadding='5' cellspacing='0'>
	<tr>
		
		<th>Prezime</th>
		<th>Ime</th>
		<th>Username</th>
		<th>Uloga</th>
		<th>Opcije</th>
	</tr>
	<?php echo $this->partialLoop('partials/_user-row.phtml', $this->users); ?>
	</table>
	<?php 
} else {
?>
<p>You do not have any users yet.</p>
<?php } ?>
<p><a href='<?php echo $this->baseUrl()?>/users/index/create'>Create a new user</a></p>
