<?php 
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<?php echo $this->headMeta(); ?>
	<?php 
	echo $this->headTitle();
	?>
	<?php echo $this->headStyle(); ?>
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
<style type="text/css">
.useraccount_personalinfo{
	float:left;
	margin:20px;
}

.useraccount_contactinfo{
	float:left;
	margin:20px;
}

.useraccount_additionalinfo{
	float:left;
	margin:20px;
}

.useraccount_avatarimg{
	float:left;
	margin:20px;
}
</style>
	</head>
<body>
<div>
<h2 align="center"><a style="margin-left:25px;" href="<?php echo $this->baseUrl(""); ?>">Početna</a></h2>
<a style="margin-left:25px;" href="<?php 
if(isset($_SERVER['HTTP_REFERER']) && $_SERVER['HTTP_REFERER'] != NULL)
{
	echo $_SERVER['HTTP_REFERER']; 
}
else
{
	echo $this->baseUrl("");
}
?>">Nazad</a>
</div>
<?php
	 echo $this->layout()->content;
?>
</body>
</html>