<?php
$this->layout()->nav = $this->action('index','index','kategorija',
array('kategorija'=> $this->kategorija, 'podkategorija' => $this->podkategorija));

$provera = $this->action('provera','index','kategorija',
array('kategorija'=> $this->kategorija, 'podkategorija' => $this->podkategorija));

?>
<h1>Uslovi korišćenja</h1>
<p>OglasiNis.com je internet portal namenjen postavljanju malih oglasa,
	prvenstveno za grad Niš, ali je moguće postavljati oglase i za druge
	gradove. Korišćenjem bilo kog dela portala OglasiNis.com, prihvatate
	sva ovde navedena pravila korišćenja. Vlasnik portala OglasiNis.com
	zadržava pravo brisanja svih oglasa koji nisu u skladu sa pravilima
	korišćenja.</p>


<p>Vlasnik portala OglasiNis.com nije odgovoran za sadržaj i tačnost
	objavljenih oglasa kao ni za eventualni štetu koja može nastati
	korišćenjem takvih oglasa. Sve sadržaje portala OglasiNis.com koristite
	na vlastitu odgovornost te vlasnik ne može biti odgovoran za štetu
	nastalu nepravilnim funkcionisanjem portala. Pristup portalu
	OglasiNis.com i svim njegovim sadržajima dozvoljen je osobama bilo kog
	uzrasta.</p>

<p>Portal OglasiNis.com predstavlja posrednički sistem između oglašavača
	i korisnika oglasa. Postavljanjem oglasa na portal OglasiNis.com ne
	dobijate garanciju da će Vaš oglas biti uspešan. Svi oglasi na portalu
	OglasiNis.com će biti vidljivi najmanje 30 dana nakon čega mogu biti
	izbrisani iz baze samog portala.</p>
<p>
	Na OglasiNis.com nije dozvoljeno:<br> - postavljanje oglasa sa
	vulgarnim rečima i pornografskim sadržajem<br> - postavljanje oglasa
	koji podstiču na mržnju i nasilje bilo kakvog oblika<br> - postavljanje
	oglasa u tuđe ime bez saglasnosti osobe u čije ime se oglas postavlja<br>
	- postavljanje linkova ka drugim veb stranama i portalima.<br> -
	postavljati oglas iste sadržine više puta u vremenskom intervalu od tri
	dana
<p>Ni jedan deo portala OglasiNis.com ne sme se koristiti u nezakonite
	svrhe, ni za promovisanje istih.</p>

<p>Svaki korisnik portala OglasiNis.com prihvatanjem ovih pravila
	dozvoljava upotrebu i obradu ličnih podataka za potrebe pravilnog
	funkcionisanja portala. Korisnik se slaže sa povremenim primanjem
	elektronske pošte koja može da sadrži reklamne poruke.</p>



<p>Zabranjeno je kopiranje i korišćenje bilo kojeg dela portala
	OglasiNis.com, uključujući i podatke koje objave korisnici bez
	izričitog odobrenja vlasnika. Ukoliko smatrate da su OglasiNis.com
	povredili Vaša autorska prava, kontaktirajte nas putem elektronske
	pošte i mi ćemo Vaš slučaj odmah razmotriti, a sporni sadržaji biće
	uklonjeni ako se utvrdi istinitost povrede Vaših autorskih prava.</p>
