<h2>Promena lozinke</h2>
<br />

<?php
if($this->message == NULL)
{
	echo "Uspešno ste promenili lozinku!<br />";
?>

<?php 
}
else
{
	if($this->recovery)
	{
?>
		<p style='color:red;'>Trenutno koristite privremenu lozinku!</p>
		<br />
<?php 
	}
	if($this->message != "1")
	{
		echo $this->message . "<br />";
	}
	echo $this->form;
}
?>
<p>
<a style="margin:0;" href='<?php echo $this->baseUrl(); ?>/users/useraccount'>Nazad</a>
</p>