<script type="text/javascript" src="<?php echo $this->baseUrl();?>/jquery/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/jquery/jquery.lightbox-0.5.js"></script>
   
<style type="text/css">
	/* jQuery lightBox plugin - Gallery style */
	.gallery {
		float:left;
		padding: 0px;
		margin:0px;
	}
	.gallery ul { padding:0px; margin:0px; list-style: none; }
	.gallery ul li { display: inline;}
	.gallery ul img {
		border: 1px solid #3e3e3e;
	}
	.gallery ul a:hover img {
		border: 1px solid #fff;
		color: #fff;
	}
	.gallery ul a:hover { color: #fff; }
</style>
<h1>
<?php
echo ($this->podkategorija ? $this->podkategorija ." - " : "") . $this->kategorija ." - Oglasi Niš&nbsp;<br>";
?>
</h1>
<?php
$dateTemp = new DateTime ( "", new DateTimeZone ( 'Europe/Belgrade' ) );
$date = strtotime ( "+0 day", strtotime ( date ( $dateTemp->format ( 'd-m-Y' ) ) ) );
$datum = date ( "Y-m-d", $date );
if ($this->paginator->count() > 0) 
{
   // remove the system parameters
	unset ( $this->params ['module'] );
	unset ( $this->params ['controller'] );
	unset ( $this->params ['action'] );
	unset ( $this->params ['cenaod'] );
	unset ( $this->params ['cenado'] );
	unset ( $this->params ['valuta'] );
	unset ( $this->params ['submit'] );
?>
<div id="formaKriterijumi_Oglas">
<?php
	echo $this->searchForm;
?>
</div>
<?php
   echo "<div class='paginationControl_Oglas'>";
   //ispis podkategorija
   if(count($this->podkategorije) > 0)
      echo "<div style='float:left;'>";
   foreach ($this->podkategorije as $id => $aRow)
   {
      if($this->kategorijaID == $aRow["kategorija"])
      {
         if($this->params["oblast"] == $id)
         {
            echo "<a style='float:left; color:#524E47;'>". $aRow["label"] ." ("
               . number_format($aRow["count"]) .")</a> ";
         }
         else
         {
            echo "<a style='float:left;'href=\"". $this->baseUrl() ."/oglasi/index/kategorija/{$this->kategorijaID}/oblast/{$id}\">"
                  . $aRow["label"] ." (".number_format($aRow["count"]).")</a> ";
         }
      }
   }
   if(count($this->podkategorije) > 0)
      echo "</div>";
   //ispis navigacije
   $current_page = ($this->params["page"] ? $this->params["page"] : 1);
   echo  "<div class='paginationControl_Oglas' style='float:left;text-align:center;'><br>Prikazano: ". 
               ( ($current_page - 1) * $this->paginator->getItemCountPerPage() + 1) 
         ." - ". ( ($current_page - 1) * $this->paginator->getItemCountPerPage() + $this->paginator->getCurrentItemCount())
         . " od ". number_format($this->paginator->getTotalItemCount()) . " oglasa "
         ."<br>";
   echo "Strana: " . ($this->params["page"] > 1 ? $this->params["page"] : 1)
      . " od ". $this->paginator->count()
      . "<br>";
    
   if($current_page > 1)
   {
      if($this->paginator->count() > 3)
         echo "<a title='Prva strana' href=\"". 
            $this->url ( array_merge ( $this->params, array ('page' => 1 ) ) ) ."\">&laquo;&laquo; Prva</a>";
          
      echo "<a title='Prethodna strana' href=\"". 
          $this->url ( array_merge ( $this->params, array ('page' => ($current_page - 1) ) ) ) ."\">&laquo; Prethodna</a>";
   }
   else 
   {
      if($this->paginator->count() > 3)
         echo "<a title='Prva strana' style='color:#524E47;'>&laquo;&laquo; Prva</a>";
      echo "<a title='Prethodna strana' style='color:#524E47;'>&laquo; Prethodna</a>";
   }
   
   if($current_page < $this->paginator->count())
   {
      echo "<a title='Sledeća strana' href=\"". 
         $this->url ( array_merge ( $this->params, array ('page' => ($current_page + 1) ) ) ) ."\">Sledeća &raquo;</a>";

      if($this->paginator->count() > 3)
         echo "<a title='Poslednja strana' href=\"". 
            $this->url ( array_merge ( $this->params, array ('page' => $this->paginator->count() ) ) ) ."\">Poslednja &raquo;&raquo;</a>";
   }
   else
   {
      echo "<a title='Sledeća strana' style='color:#524E47;'>Sledeća &raquo;</a>";
      if($this->paginator->count() > 3)
         echo "<a title='Poslednja strana' style='color:#524E47;'>Poslednja &raquo;&raquo;</a>";
   }
   echo "<br><br></div></div>";

   $this->currentItemCount = $this->paginator->getCurrentItemCount();
   $this->itemCountPerPage = $this->paginator->getItemCountPerPage();
   
   //ispis svih oglasa na strani
   echo $this->partialLoop ( 'partials/_page-oglasiprikaz.phtml', $this->paginator );
	//ispis navigacije na dnu
   echo $this->paginationControl ( $this->paginator, 'Sliding', 'partials/_page-paginationcontrol.phtml', array("params" => $this->params) );

} 
else 
{
?>
<div class="formaKriterijumi_Oglas">
<?php
	echo $this->searchForm;
?>
</div>
<br>
<?php if($_POST){?>
<h2>Nema oglasa za izabrane kriterijume</h2>
<?php }else{?>
<h2>Nema unetih oglasa
<a href='<?php
	echo $this->baseUrl ( 'oglas/unosoglasa/ ' );
	?>'> DODAJ OGLAS </a></h2><?php
   }
}
?>
