<script type="text/javascript" src="<?php echo $this->baseUrl();?>/jquery/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/jquery/jquery.lightbox-0.5.js"></script>
   
<style type="text/css">
	/* jQuery lightBox plugin - Gallery style */
	.gallery {
		float:left;
		padding: 0px;
		margin:0px;
	}
	.gallery ul { padding:0px; margin:0px; list-style: none; }
	.gallery ul li { display: inline;}
	.gallery ul img {
		border: 1px solid #3e3e3e;
	}
	.gallery ul a:hover img {
		border: 1px solid #fff;
		color: #fff;
	}
	.gallery ul a:hover { color: #fff; }
</style>
<h1>Grad Niš&nbsp;-&nbsp;Svi oglasi</h1>
<?php
if ($this->paginator->count() > 0)  
{
   // remove the system parameters
	unset ( $this->params ['module'] );
	unset ( $this->params ['controller'] );
	unset ( $this->params ['action'] );
	unset ( $this->params ['cenaod'] );
	unset ( $this->params ['cenado'] );
	unset ( $this->params ['valuta'] );
	unset ( $this->params ['submit'] );
?>
<div id="formaKriterijumi_Oglas">
<?php
	echo $this->searchForm;
?>
</div>
<?php  

   $current_page = ($this->params["page"] > 1 ? $this->params["page"] : 1);
   $current_page = ($current_page > $this->paginator->count() ? $this->paginator->count() : $current_page);
   
   echo  "<div class='paginationControl_Oglas'>"
         ."Prikazano: ". ( ($current_page - 1) * 10 + 1) 
         ." - ". ( ($current_page - 1) * 10 + $this->paginator->getCurrentItemCount())
         . " od ". number_format($this->paginator->getTotalItemCount()) . " oglasa "
         ."<br>";
   echo "Strana: " . $current_page
      . " od ". $this->paginator->count()
      . "<br><br>";
    
   if($current_page > 1)
   {
      echo "<a title='Prva strana' href=\"". 
         $this->url ( array_merge ( $this->params, array ('page' => 1 ) ) ) ."\">&laquo;&laquo; Prva</a>";
          
      echo "<a title='Prethodna strana' href=\"". 
          $this->url ( array_merge ( $this->params, array ('page' => ($current_page - 1) ) ) ) ."\">&laquo; Prethodna</a>";
   }
   else 
   {
      echo "<a title='Prva strana' style='color:black;'>&laquo;&laquo; Prva</a>";
      echo "<a title='Prethodna strana' style='color:black;'>&laquo; Prethodna</a>";
   }
   
   if($current_page < $this->paginator->count())
   {
      echo "<a title='Sledeća strana' href=\"". 
          $this->url ( array_merge ( $this->params, array ('page' => ($current_page + 1) ) ) ) ."\">Sledeća &raquo;</a>";
          
      echo "<a title='Poslednja strana' href=\"". 
          $this->url ( array_merge ( $this->params, array ('page' => $this->paginator->count() ) ) ) ."\">Poslednja &raquo;&raquo;</a>";
   }
   else
   {
      echo "<a title='Sledeća strana' style='color:black;'>Sledeća &raquo;</a>";
      echo "<a title='Poslednja strana' style='color:black;'>Poslednja &raquo;&raquo;</a>";
   }

   echo "<br><br></div>";
   
   echo $this->partialLoop ( 'partials/_page-oglasiprikaz.phtml', $this->paginator );
	echo $this->paginationControl ( $this->paginator, 'Sliding', 'partials/_page-paginationcontrol.phtml', array("params" => $this->params) );

} 
else 
{
?>
	<div class="formaKriterijumi_Oglas">
<?php
	echo $this->searchForm;
	
	?></div>
		<br>
<?php if($_POST){?>
<h2>Nema oglasa za izabrane kriterijume</h2>
<?php }else{?>
<h2>Nema unetih oglasa
<a href='<?php
	echo $this->baseUrl ( 'oglas/unosoglasa/ ' );
	?>'> DODAJ OGLAS </a></h2><?php
   }
}
?>

